// SPDX-License-Identifier: MPL-2.0
/* Reusable local artwork, kept beside the selected action rather than a workspace tab. */
(function(){
 const $=id=>document.getElementById(id);let db,items=[],target;
 const ready=new Promise((resolve,reject)=>{const r=indexedDB.open('decklab-artwork',1);r.onupgradeneeded=()=>r.result.createObjectStore('images',{keyPath:'id'});r.onsuccess=()=>{db=r.result;resolve()};r.onerror=()=>reject(r.error);});ready.catch(()=>{});
 async function tx(mode,operation){await ready;return new Promise((resolve,reject)=>{const t=db.transaction('images',mode),r=operation(t.objectStore('images'));t.oncomplete=()=>resolve(r.result);t.onerror=()=>reject(t.error);t.onabort=()=>reject(t.error||Error('Storage cancelled.'));});}
 function context(kind='action'){return {kind,device:profileState.target,page:profilePage(),placement:selectedProfilePlacement(),part:window.DeckLabDisplayArtwork?.selected()};}
 function valid(t){return t&&!window.decklabLivePreview&&t.device===profileState.target&&t.page===profilePage()&&(t.kind==='display'?t.part===DeckLabDisplayArtwork.selected():profileState.placements.includes(t.placement)&&selectedProfilePlacement()===t.placement);}
 function apply(item,t=target){
  if(!valid(t))throw Error('Selection changed. Close the library and choose the target again in Build.');
  const artworkCredit={name:item.name,pack:item.pack,author:item.author,license:item.license,licenseText:item.licenseText,sourcePath:item.sourcePath};
  const patch=(item.role==='background'||(!item.role&&item.pack==='Elgato colour templates'))?{background:{image:item.data,fit:'cover',template:item.template||null,artworkCredit}}:{image:item.data,fit:item.fit||'contain',artworkCredit};
  if(t.kind==='display')DeckLabDisplayArtwork.edit(patch);else DeckLabVisuals.commit(t.placement,patch);
 }
 async function open(kind='action'){if(window.decklabLivePreview)return;target=context(kind);const d=$('artworkDialog');d.classList.remove('artwork-docked');d.showModal();note('');try{await refresh()}catch(e){note('Artwork storage is unavailable in this browser.')}}
 const note=text=>$('artworkStatus').textContent=text;
 async function refresh(){items=await tx('readonly',s=>s.getAll());draw();}
 function draw(){const q=$('artworkSearch').value.toLowerCase(),grid=$('artworkGrid');grid.replaceChildren();const source=$('artworkSource')?.value;if(source==='samples'){window.DeckLabElgatoIcons?.cancel();return DeckLabSamples.draw(grid,q,target);}window.DeckLabSamples?.cancel();if(source==='elgato')return DeckLabElgatoIcons.draw(grid,q,target);window.DeckLabElgatoIcons?.cancel();const found=items.filter(i=>(i.name+' '+(i.pack||'')+' '+(i.tags||[]).join(' ')).toLowerCase().includes(q)&&($('artworkFilter').value!=='favourites'||i.favourite)).sort((a,b)=>$('artworkFilter').value==='recent'?(b.usedAt||0)-(a.usedAt||0):a.name.localeCompare(b.name));$('artworkEmpty').hidden=!!found.length;$('artworkEmpty').textContent=items.length?'No artwork matches your search.':'Your reusable artwork will appear here. Upload PNG, JPEG, GIF or WebP.';
  for(const item of found){const card=document.createElement('div');card.className='artwork-card';const use=document.createElement('button');use.type='button';use.className='artwork-use';use.title=[item.name,item.pack,item.author,item.license].filter(Boolean).join(' · ');use.draggable=true;use.ondragstart=e=>{e.dataTransfer.setData('application/x-decklab-artwork',item.id);e.dataTransfer.effectAllowed='copy';};const img=new Image();img.src=item.data;img.alt='';const name=document.createElement('span');name.textContent=item.name;use.append(img,name);use.onclick=async()=>{try{apply(item)}catch(e){note(e.message);return;}await tx('readwrite',s=>s.put({...item,usedAt:Date.now()}));$('visualMessage').textContent=item.name+' · '+item.width+' × '+item.height;$('artworkDialog').close();};
  const remove=document.createElement('button');remove.type='button';remove.className='artwork-remove';remove.textContent='×';remove.title='Remove from library; placed images stay unchanged';remove.setAttribute('aria-label','Remove '+item.name+' from library');remove.onclick=async()=>{try{await tx('readwrite',s=>s.delete(item.id));await refresh();note('Removed from library. Images already on your deck are unchanged.');}catch(e){note('Could not remove artwork: '+e.message)}};const fav=document.createElement('button');fav.className='artwork-favourite';fav.textContent=item.favourite?'★':'☆';fav.setAttribute('aria-label','Favourite '+item.name);fav.setAttribute('aria-pressed',!!item.favourite);fav.onclick=async()=>{try{await tx('readwrite',s=>s.put({...item,favourite:!item.favourite}));await refresh()}catch(e){note(e.message)}};card.append(use,remove,fav);grid.append(card);}
 }
 async function decode(data){if(typeof data!=='string'||!/^data:image\/(png|jpeg|gif|webp);base64,/.test(data)||data.length>12*1024*1024)throw Error('Use PNG, JPEG, GIF or WebP up to 8 MB.');const img=new Image();img.src=data;await img.decode();return {width:img.naturalWidth,height:img.naturalHeight};}
 async function add(name,data,meta={}){await ready;items=await tx('readonly',s=>s.getAll());const size=await decode(data);const duplicate=items.find(i=>i.data===data);if(duplicate)return;if(items.length>=1000||items.reduce((n,i)=>n+i.data.length,0)+data.length>60*1024*1024)throw Error('Artwork library is full. Export a backup and remove unused entries.');await tx('readwrite',s=>s.put({id:crypto.randomUUID?crypto.randomUUID():Date.now()+'-'+Math.random(),name:String(name).slice(0,160),data,...size,pack:String(meta.pack||''),author:String(meta.author||''),version:String(meta.version||''),license:String(meta.license||''),licenseText:String(meta.licenseText||''),tags:Array.isArray(meta.tags)?meta.tags.map(String):[],favourite:!!meta.favourite,usedAt:Number(meta.usedAt)||0,sourcePath:String(meta.sourcePath||''),svgRasterized:!!meta.svgRasterized,role:meta.role==='background'?'background':'foreground',template:meta.role==='background'?meta.template||null:null}));await refresh();}
 function download(data,name){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data)],{type:'application/json'}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
 function boot(){if(!$('visualImageInput'))return;
 const d=document.createElement('dialog');d.id='artworkDialog';d.setAttribute('aria-labelledby','artworkHeading');d.innerHTML='<div class="artwork-heading"><div><h2 id="artworkHeading">My artwork</h2><p>Reusable images for your keys and LCD surfaces.</p></div><button id="artworkClose" type="button" aria-label="Close artwork library">×</button></div><div class="artwork-tools"><input id="artworkSearch" type="search" aria-label="Search artwork" placeholder="Search artwork…"><button id="artworkUpload" type="button">Upload images</button><button id="artworkExport" class="secondary" type="button" title="Save a portable backup of your artwork">Export</button><button id="artworkImport" class="secondary" type="button" title="Restore an exported artwork collection">Import</button></div><input id="artworkFiles" type="file" accept="image/png,image/jpeg,image/gif,image/webp" multiple hidden><input id="artworkBackup" type="file" accept="application/json,.json" hidden><p id="artworkStatus" role="status"></p><div id="artworkGrid"></div><p id="artworkEmpty"></p><p class="artwork-storage-note">Stored in this browser. Export a backup before clearing browser data. Profile exports include placed images.</p>';
 document.body.append(d);const tools=d.querySelector('.artwork-tools');const filter=document.createElement('select');filter.id='artworkFilter';filter.setAttribute('aria-label','Artwork filter');for(const [v,t] of [['all','All artwork'],['favourites','Favourites'],['recent','Recently used']])filter.add(new Option(t,v));filter.onchange=draw;tools.append(filter);for(const [id,text] of [['artworkPack','Import icon pack'],['artworkFolder','Import pack folder'],['artworkDock','Dock beside deck']]){const b=document.createElement('button');b.id=id;b.textContent=text;b.type='button';tools.append(b);}const old=$('visualImageInput').closest('label');old.style.display='none';const b=document.createElement('button');b.type='button';b.id='openArtworkLibrary';b.textContent='Choose image / icon';old.before(b);b.onclick=()=>open();

 const packInput=document.createElement('input');packInput.type='file';packInput.accept='.sdIcons,.streamDeckIconPack,.zip';packInput.hidden=true;packInput.id='artworkPackFile';d.append(packInput);
 const folderInput=document.createElement('input');folderInput.type='file';folderInput.webkitdirectory=true;folderInput.hidden=true;folderInput.id='artworkPackFolder';d.append(folderInput);
 $('artworkPack').onclick=()=>packInput.click();$('artworkFolder').onclick=()=>folderInput.click();$('artworkDock').onclick=()=>{d.close();d.classList.add('artwork-docked');d.show();note('Drag artwork onto a key or LCD surface. Close this panel to return to editing.');};
 async function importPack(files){const pack=await DeckLabIconPack.read(files);for(const i of pack.entries)await decode(i.data);let imported=0;try{for(const i of pack.entries){await add(i.name,i.data,i.meta);imported++}}catch(e){throw Error(imported+' icons processed before storage failed: '+e.message)}note(pack.manifest.Name+' · '+imported+' icons processed. SVGs are converted to PNG; GIFs keep animation.');}
 packInput.onchange=async e=>{const f=e.target.files[0];e.target.value='';if(!f)return;try{note('Reading icon pack…');await importPack(await DeckLabNativeProfile.unzip(await f.arrayBuffer()));}catch(err){note('Pack import: '+err.message+' Use a readable ZIP package or an extracted pack folder.');}};
 folderInput.onchange=async e=>{const files=[...e.target.files];e.target.value='';try{if(files.length>5000||files.reduce((n,f)=>n+f.size,0)>64*1024*1024)throw Error('Pack exceeds import limits.');const entries=new Map();for(const f of files){if(f.size>8*1024*1024)throw Error('A pack file exceeds 8 MB.');entries.set(f.webkitRelativePath,new Uint8Array(await f.arrayBuffer()));}await importPack(entries)}catch(err){note('Pack import: '+err.message)}};
 const deck=$('profileDeck');deck.addEventListener('dragover',e=>{if(!e.dataTransfer.types.includes('application/x-decklab-artwork'))return;e.preventDefault();e.stopImmediatePropagation();e.dataTransfer.dropEffect=window.decklabLivePreview?'none':'copy';},true);
 deck.addEventListener('drop',async e=>{const id=e.dataTransfer.getData('application/x-decklab-artwork');if(!id)return;e.preventDefault();e.stopImmediatePropagation();if(window.decklabLivePreview||profileDevice().inputOnly)return;try{const node=e.target.closest('[data-art-controller]'),item=items.find(i=>i.id===id);if(!node||!item)return;let p=profilePlacementAt(node.dataset.artController,Number(node.dataset.artColumn),Number(node.dataset.artRow));if(!p)p=await createProfileActionPlacement(profileAvailableActions().findIndex(a=>a.UUID==='com.decklab.visual'),node.dataset.artController,Number(node.dataset.artColumn),Number(node.dataset.artRow));if(p){selectProfilePlacement(p);target=context();apply(item);await tx('readwrite',s=>s.put({...item,usedAt:Date.now()}));note('Applied '+item.name);}}catch(err){note(err.message)}},true);
 $('artworkClose').onclick=()=>d.close();$('artworkSearch').oninput=draw;$('artworkUpload').onclick=()=>$('artworkFiles').click();$('artworkImport').onclick=()=>$('artworkBackup').click();
 $('artworkFiles').onchange=async e=>{const files=[...e.target.files];e.target.value='';let count=0;for(const f of files){try{if(f.size>8*1024*1024)throw Error('Image exceeds 8 MB');const data=await new Promise((ok,no)=>{const r=new FileReader();r.onload=()=>ok(r.result);r.onerror=()=>no(Error('Could not read file'));r.readAsDataURL(f)});await add(f.name,data);count++;}catch(err){note('Added '+count+' image(s). '+f.name+': '+err.message);return;}}note('Added '+count+' image(s). Select one to apply it.');};
 $('artworkExport').onclick=()=>download({format:'DeckLabArtwork',version:1,images:items},'decklab-artwork.json');
 $('artworkBackup').onchange=async e=>{const f=e.target.files[0];e.target.value='';if(!f)return;try{if(f.size>64*1024*1024)throw Error('Backup exceeds 64 MB.');const data=JSON.parse(await f.text());if(data.format!=='DeckLabArtwork'||data.version!==1||!Array.isArray(data.images)||data.images.length>1000)throw Error('Not a supported artwork backup.');for(const i of data.images)await decode(i.data);for(const i of data.images)await add(i.name||'Untitled',i.data,i);note('Artwork imported. Duplicates were skipped.');}catch(err){note('Import could not finish: '+err.message)}};
 }
 window.DeckLabArtwork={add,refresh,draw,open,apply,get target(){return target}};
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(boot,220));else setTimeout(boot,220);
})();
