// SPDX-License-Identifier: MPL-2.0
/* Static raster composition. Recipes remain editable in profile data. */
(function(){
 const $=id=>document.getElementById(id);let target,original,state=0,recipes={},image=null,sourceData=null,sourceCredit=null,preview=null,token=0;
 const fields=['background','transparent','text','colour','size','align','fit','zoom','x','y'];
 const defaults=()=>({background:'#152334',transparent:!!DeckLabVisuals.visual({customVisual:original,state}).background,text:'',colour:'#ffffff',size:24,align:'center',fit:'contain',zoom:1,x:0,y:0});
 const api=window.DeckLabCreator={isPreview:p=>preview?.id===p.id,get preview(){return preview}};
 function dimensions(){return target.controller==='Encoder'?[200,100]:target.controller==='Neo'?[232,50]:[144,144];}
 function read(){const r={};for(const k of fields){const e=$('creator-'+k);r[k]=e.type==='checkbox'?e.checked:e.type==='number'||e.type==='range'?Number(e.value):e.value;}return r;}
 function write(r){for(const k of fields){const e=$('creator-'+k);if(e.type==='checkbox')e.checked=!!r[k];else e.value=r[k];}}
 function draw(){if(!target||!profileState.placements.includes(target))return;const r=recipes[state]=read(),[w,h]=dimensions(),c=$('creatorCanvas');c.width=w;c.height=h;const ctx=c.getContext('2d');ctx.clearRect(0,0,w,h);if(!r.transparent){ctx.fillStyle=r.background;ctx.fillRect(0,0,w,h);}if(image){const scale=(r.fit==='cover'?Math.max(w/image.width,h/image.height):Math.min(w/image.width,h/image.height))*r.zoom,iw=image.width*scale,ih=image.height*scale;ctx.drawImage(image,(w-iw)/2+r.x*w/100,(h-ih)/2+r.y*h/100,iw,ih);}ctx.fillStyle=r.colour;ctx.textAlign=r.align;ctx.textBaseline='middle';ctx.font=`600 ${Math.max(6,Math.min(72,r.size))}px Arial`;const lines=r.text.split('\n').slice(0,5);lines.forEach((line,i)=>ctx.fillText(line,r.align==='left'?8:r.align==='right'?w-8:w/2,h/2+(i-(lines.length-1)/2)*r.size*1.15,w-16));preview={id:target.id,state,image:c.toDataURL('image/png')};renderProfileDeck();}
 async function loadSource(){const stamp=++token;image=null;sourceCredit=original?.creator?.sourceCredit||DeckLabVisuals.visual(target).artworkCredit||null;const src=sourceData=original?.creator?original.creator.source:DeckLabVisuals.resolve(target).image;if(src){const im=new Image();im.src=src;try{await im.decode();if(stamp!==token)return;image=im}catch(e){$('creatorStatus').textContent='Source image could not be decoded.';}}if(stamp===token)draw();}
 function stop(){preview=null;target=null;token++;$('assetCreator').hidden=true;renderProfileDeck();}
 function boot(){const b=document.createElement('button');b.id='openAssetCreator';b.type='button';b.className='secondary';b.textContent='Create / edit asset';$('visualReset').before(b);const panel=document.createElement('section');panel.id='assetCreator';panel.hidden=true;panel.innerHTML='<h3>Foreground asset creator</h3><p class="hint">Background template stays separate. Static PNG · GIF artwork becomes a still image. A/B artwork follows the action’s state.</p><label>Artwork state<select id="creatorState"><option value="0">A</option><option value="1">B</option></select></label><div class="creator-preview"><canvas id="creatorCanvas"></canvas><div id="creatorSafe"></div></div><label><input id="creatorSafeToggle" type="checkbox" checked> Show safe-area guide</label><div class="visual-fields"><label>Background<input id="creator-background" type="color"></label><label>Text colour<input id="creator-colour" type="color"></label></div><label><input id="creator-transparent" type="checkbox"> Transparent background</label><label>Text<textarea id="creator-text" rows="2"></textarea></label><div class="visual-fields"><label>Text size<input id="creator-size" type="number" min="6" max="72"></label><label>Alignment<select id="creator-align"><option value="left">Left</option><option value="center">Centre</option><option value="right">Right</option></select></label><label>Image fit<select id="creator-fit"><option value="contain">Fit</option><option value="cover">Fill</option></select></label><label>Zoom<input id="creator-zoom" type="range" min="0.25" max="3" step="0.05"></label><label>Image X<input id="creator-x" type="range" min="-100" max="100"></label><label>Image Y<input id="creator-y" type="range" min="-100" max="100"></label></div><div class="creator-actions"><button id="creatorApply" type="button" class="secondary">Apply</button><button id="creatorSave" type="button" class="secondary">Save to artwork</button><button id="creatorCancel" type="button" class="secondary">Cancel</button></div><p id="creatorStatus" role="status" class="hint"></p>';$('placementVisuals').append(panel);
 b.onclick=()=>{target=selectedProfilePlacement();if(!target||window.decklabLivePreview)return;original=deepClone(DeckLabVisuals.normalize(target.customVisual));state=0;recipes=deepClone(original?.creator?.recipes||{});$('creatorState').value='0';write({...defaults(),...recipes[0]});panel.hidden=false;$('creatorStatus').textContent='Preview only until Apply. Safe-area guide is not exported.';loadSource();};fields.forEach(k=>$('creator-'+k).oninput=draw);$('creatorState').onchange=e=>{state=Number(e.target.value);write({...defaults(),...recipes[state]});draw();};$('creatorSafeToggle').onchange=e=>$('creatorSafe').hidden=!e.target.checked;$('creatorCancel').onclick=stop;
 $('creatorApply').onclick=()=>{if(!target||!profileState.placements.includes(target)||window.decklabLivePreview)return;const states={...original?.states};const current=state;for(const key of Object.keys(recipes)){state=Number(key);write(recipes[key]);draw();states[key]={...states[key],artworkCredit:sourceCredit,image:preview.image,showTitle:false,title:''};}state=current;write(recipes[state]);const source=sourceData||null;const p=target;preview=null;DeckLabVisuals.commit(p,{states,creator:{source,sourceCredit,recipes:deepClone(recipes)}});stop();};
 $('creatorSave').onclick=async()=>{try{if(preview)await DeckLabArtwork.add('Created asset '+(state?'B':'A'),preview.image,{...sourceCredit,tags:['created']});$('creatorStatus').textContent='Saved to My artwork.';}catch(e){$('creatorStatus').textContent=e.message}};
 const select=selectProfilePlacement;selectProfilePlacement=function(p,options){if(target&&p?.id!==target.id)stop();return select(p,options)};
 }
 document.addEventListener('DOMContentLoaded',()=>setTimeout(boot,260));
})();
