// SPDX-License-Identifier: MPL-2.0
/* Full-display and segment artwork layers. These are page artwork, not extra SDK actions. */
(function(){
 const $=id=>document.getElementById(id),safe=s=>typeof s==='string'&&/^data:image\/(png|jpeg|gif|webp);base64,/.test(s);
 function spec(){const key=profileState.target;if(key==='plus'||key==='plusxl')return {count:key==='plus'?4:6,names:[],kind:'strip'};if(key==='galleon')return {count:4,names:['top left','bottom left','top right','bottom right'],kind:'screen'};return null;}
 function config(){const c=profilePage()?.displayArtwork?.[profileState.target]||{};if(profileState.target==='galleon'&&c.layoutVersion!==2){if(c.sources)c.sources=Object.fromEntries(Object.entries(c.sources).filter(([id])=>!id.startsWith('segment-')).map(([id,n])=>[id,Math.min(3,(Number(n)||0)*2)]));c.layoutVersion=2;}return c;}
 function selected(){return $('displayPart')?.value||'full';}
 function edit(patch){if(window.decklabLivePreview)return;const page=profilePage();if(!page||!spec())return;profilePushHistory('edit display artwork');page.displayArtwork||={};const c=page.displayArtwork[profileState.target]||={};const part=selected();c[part]={...c[part],...patch};renderProfileDeck();profileScheduleAutosave();}
 function rects(surface){const key=profileState.target,g=surface._geom,d=profileDevice(),S=DeckLabSurface;let full,segments=[];
 if(key==='galleon'){full={x:188,y:400,w:732,h:396};segments=[{x:209,y:421,w:338,h:178},{x:209,y:609,w:338,h:178},{x:561,y:421,w:338,h:178},{x:561,y:609,w:338,h:178}];}
 else{for(let i=0;i<d.dials;i++)segments.push(S.controlRect(key,d,g,'touch',i,i,0));full={...segments[0],w:segments.reduce((n,r)=>n+r.w,0)};}
 return {full,segments};}
 function modeOf(id){return id==='full'?'full':id.startsWith('vertical-')?'vertical':id.startsWith('horizontal-')?'horizontal':'segments';}
 function regions(surface,mode=config().mode||'segments'){const {full:f,segments}=rects(surface);if(mode==='full')return [['full',f]];if(mode==='vertical')return [0,1].map(i=>['vertical-'+i,{x:f.x+i*f.w/2,y:f.y,w:f.w/2,h:f.h}]);if(mode==='horizontal')return [0,1].map(i=>['horizontal-'+i,{x:f.x,y:f.y+i*f.h/2,w:f.w,h:f.h/2}]);return segments.map((r,i)=>['segment-'+i,r]);}
 function render(){const s=spec(),surface=$('profileDeck')?.querySelector('.ds-surface');if(!s||!surface){sync();return;}surface.querySelectorAll(':scope > .display-art-layer').forEach(n=>n.remove());const c=config(),g=surface._geom,{full,segments}=rects(surface);surface.classList.add('has-display-artwork');surface.classList.toggle('display-feedback-hidden',c.feedback===false);
 const layer=(id,r)=>{const v=c[id]||{},node=document.createElement('div');node.className='display-art-layer';node.dataset.displayPart=id;Object.assign(node.style,{left:r.x/g.w*100+'%',top:r.y/g.h*100+'%',width:r.w/g.w*100+'%',height:r.h/g.h*100+'%',background:v.opaque||(id==='full'&&profileState.target==='galleon')?'#000':'transparent',zIndex:id==='full'?'3':'4'});if(safe(v.image)){const im=new Image();im.src=v.image;im.alt='';im.style.objectFit=v.fit==='contain'?'contain':'cover';node.append(im);}surface.append(node);};
 layer('full',full);for(const [id,r] of regions(surface))if(id!=='full')layer(id,r);sync();}
 function sync(){const box=$('displayArtworkEditor');if(!box)return;const s=spec();box.hidden=!s;if(!s)return;const select=$('displayPart'),prev=select.value;if(select.dataset.device!==profileState.target){select.replaceChildren(new Option(s.kind==='strip'?'Full touch strip':'Full LCD screen','full'));for(let i=0;i<s.count;i++)select.add(new Option('Segment '+(i+1)+(s.names[i]?' · '+s.names[i]:''),'segment-'+i));for(const [v,t] of [['vertical-0','Left half'],['vertical-1','Right half'],['horizontal-0','Top half'],['horizontal-1','Bottom half']])select.add(new Option(t,v));select.dataset.device=profileState.target;if([...select.options].some(o=>o.value===prev))select.value=prev;}const c=config(),v=c[select.value]||{};$('displayOpaque').checked=!!v.opaque;$('displayFit').value=v.fit==='contain'?'contain':'cover';$('displayFeedback').checked=c.feedback!==false;const img=$('displayArtworkPreview');img.hidden=!safe(v.image);if(safe(v.image))img.src=v.image;else img.removeAttribute('src');$('displayRemove').disabled=!v.image;$('displayLayoutNote').textContent=s.kind==='strip'?s.count+' segments, left to right. Segment images and opaque fills cover the full-strip background.':'Segments 1/2 are on the left; 3/4 on the right. Transparent regions reveal the full-screen background.';}
 function boot(){const box=document.createElement('details');box.id='displayArtworkEditor';box.className='studio-details';box.innerHTML='<summary>LCD artwork · full screen & segments</summary><label>Artwork area<select id="displayPart"></select></label><img id="displayArtworkPreview" alt="Display artwork preview" hidden><label class="file-button">Upload image<input id="displayImageInput" type="file" accept="image/png,image/jpeg,image/gif,image/webp"></label><label>Image fit<select id="displayFit"><option value="cover">Fill</option><option value="contain">Fit</option></select></label><label class="display-checkbox"><input id="displayOpaque" type="checkbox"> Opaque black background</label><label class="display-checkbox"><input id="displayFeedback" type="checkbox" checked> Show action feedback above artwork</label><button id="displayRemove" class="secondary" type="button">Remove image</button><p id="displayLayoutNote" class="hint"></p><p id="displayArtworkStatus" class="hint" role="status"></p>';document.querySelector('.builder-inspector-panel').prepend(box);$('displayPart').onchange=sync;$('displayFit').onchange=e=>edit({fit:e.target.value});$('displayOpaque').onchange=e=>edit({opaque:e.target.checked});$('displayRemove').onclick=()=>edit({image:null});$('displayFeedback').onchange=e=>{if(window.decklabLivePreview)return;profilePushHistory('toggle display feedback');const p=profilePage();p.displayArtwork||={};p.displayArtwork[profileState.target]||={};p.displayArtwork[profileState.target].feedback=e.target.checked;renderProfileDeck();profileScheduleAutosave();};
 $('displayImageInput').onchange=async e=>{const f=e.target.files?.[0];e.target.value='';if(!f)return;const page=profilePage(),device=profileState.target,part=selected();try{if(f.size>8*1024*1024)throw Error('Choose an image below 8 MB.');const data=await new Promise((ok,no)=>{const r=new FileReader();r.onload=()=>ok(r.result);r.onerror=()=>no(Error('Could not read image'));r.readAsDataURL(f)});if(!safe(data))throw Error('Choose PNG, JPEG, GIF or WebP.');const img=new Image();img.src=data;await img.decode();if(page!==profilePage()||device!==profileState.target||part!==selected())throw Error('Selection changed. Please upload again.');edit({image:data});$('displayArtworkStatus').textContent=f.name+' · '+img.naturalWidth+' × '+img.naturalHeight;}catch(err){$('displayArtworkStatus').textContent=err.message;}};render();}
 const colourSelect=DeckLabAppearance.select;DeckLabAppearance.select=function(...args){colourSelect(...args);render();};
 const old=renderProfileDeck;renderProfileDeck=function(){old();render();};window.DeckLabDisplayArtwork={spec,config,rects,edit,regions,modeOf};document.addEventListener('DOMContentLoaded',()=>setTimeout(boot,320));
})();
