// SPDX-License-Identifier: MPL-2.0
/* Pinned, local, MIT-licensed SVG data. Imported packages are never executed. */
(function(){
 const $=id=>document.getElementById(id);let pending,catalogue,generation=0,limit=72;
 const hex=value=>/^#[a-f0-9]{6}$/i.test(value)?value:'#ffffff';
 function load(){return pending||=(fetch('assets/elgato-icons/index.json').then(r=>{if(!r.ok)throw Error('Elgato icons unavailable.');return r.json()}).then(d=>catalogue=d).catch(e=>{pending=null;throw e}));}
 function url(entry,colour){return 'data:image/svg+xml;charset=utf-8,'+encodeURIComponent(entry.svg.replace(/currentColor/g,hex(colour)));}
 function credit(entry){return {name:entry.name,pack:'Elgato Icons',author:'Corsair Memory Inc.',version:catalogue.version,license:'MIT',licenseText:catalogue.licenseText,sourcePath:catalogue.source+'/blob/main/'+entry.sourcePath,tags:['elgato',...entry.id.split('-').filter(Boolean)]};}
 async function raster(id,colour){await load();const entry=catalogue.entries.find(e=>e.id===id);if(!entry)throw Error('Unknown Elgato icon.');const im=new Image();im.src=url(entry,colour);await im.decode();const c=document.createElement('canvas');c.width=c.height=144;const x=c.getContext('2d'),scale=112/Math.max(im.naturalWidth,im.naturalHeight),w=im.naturalWidth*scale,h=im.naturalHeight*scale;x.drawImage(im,(144-w)/2,(144-h)/2,w,h);return {data:c.toDataURL('image/png'),meta:credit(entry)};}
 function apply(p,item){DeckLabVisuals.commit(p,{image:item.data,fit:'contain',artworkCredit:item.meta});}
 async function draw(grid,q,target,more=false){const stamp=++generation;if(!more)limit=72;grid.replaceChildren();$('artworkEmpty').hidden=true;$('artworkStatus').textContent='Loading Elgato icons…';try{
  await load();if(stamp!==generation||$('artworkSource').value!=='elgato')return;const filter=$('elgatoIconStyle').value,colour=hex($('elgatoIconColour').value),words=q.toLowerCase().trim().split(/\s+/).filter(Boolean),found=catalogue.entries.filter(e=>words.every(w=>(e.name+' '+e.id).toLowerCase().includes(w))&&(filter==='all'||(filter==='filled'?e.id.includes('--filled'):!e.id.includes('--filled'))));
  $('artworkStatus').textContent=found.length+' Elgato icons · MIT · Corsair Memory Inc.';$('artworkEmpty').hidden=!!found.length;$('artworkEmpty').textContent='No Elgato icons match your search.';
  for(const entry of found.slice(0,limit)){const card=document.createElement('div');card.className='artwork-card elgato-icon-card';const use=document.createElement('button');use.type='button';use.className='artwork-use';use.title=entry.name+' · Apply icon';use.dataset.iconId=entry.id;use.draggable=true;use.ondragstart=e=>{e.dataTransfer.setData('application/x-decklab-elgato-icon',JSON.stringify({id:entry.id,colour}));e.dataTransfer.effectAllowed='copy';};const im=new Image();im.loading='lazy';im.src=url(entry,colour);im.alt='';const label=document.createElement('span');label.textContent=entry.name;use.append(im,label);use.onclick=async()=>{try{const item=await raster(entry.id,colour);DeckLabArtwork.apply({data:item.data,...item.meta,fit:'contain'},target);$('artworkDialog').close();}catch(e){$('artworkStatus').textContent=e.message;}};
   const save=document.createElement('button');save.type='button';save.className='elgato-icon-save';save.textContent='+';save.setAttribute('aria-label','Save '+entry.name+' to My artwork');save.title='Save to My artwork for favourites and reuse';save.onclick=async()=>{save.disabled=true;try{const item=await raster(entry.id,colour);await DeckLabArtwork.add(entry.name,item.data,item.meta);$('artworkStatus').textContent='Saved '+entry.name+' to My artwork.';}catch(e){$('artworkStatus').textContent=e.message;}finally{save.disabled=false}};card.append(use,save);grid.append(card);
  }
  if(found.length>limit){const moreButton=document.createElement('button');moreButton.type='button';moreButton.className='elgato-icons-more';moreButton.textContent='Show more ('+(found.length-limit)+' remaining)';moreButton.onclick=()=>{limit+=72;draw(grid,q,target,true)};grid.append(moreButton);}
 }catch(e){if(stamp===generation)$('artworkStatus').textContent=e.message;}}
 function boot(){const tools=$('artworkDialog').querySelector('.artwork-tools'),source=document.createElement('select');source.id='artworkSource';source.setAttribute('aria-label','Artwork source');source.add(new Option('My artwork','mine'));source.add(new Option('Elgato icons','elgato'));tools.prepend(source);const options=document.createElement('div');options.id='elgatoIconOptions';options.hidden=true;options.innerHTML='<label>Style<select id="elgatoIconStyle"><option value="all">All icons</option><option value="outline">Regular / outline</option><option value="filled">Filled</option></select></label><label>Icon colour<input id="elgatoIconColour" type="color" value="#ffffff"></label><a href="https://github.com/elgatosf/icons" target="_blank" rel="noopener">Elgato Icons · MIT</a>';tools.after(options);
  const redraw=()=>{const built=source.value==='elgato';options.hidden=!built;for(const id of ['artworkUpload','artworkExport','artworkImport','artworkPack','artworkFolder','artworkFilter'])$(id).hidden=built;$('artworkHeading').textContent=built?'Elgato icons':'My artwork';$('artworkSearch').placeholder=built?'Search Elgato icons…':'Search artwork…';DeckLabArtwork.draw();};source.onchange=redraw;$('elgatoIconStyle').onchange=()=>DeckLabArtwork.draw();$('elgatoIconColour').oninput=()=>DeckLabArtwork.draw();
  $('profileDeck').addEventListener('dragover',e=>{if(!e.dataTransfer.types.includes('application/x-decklab-elgato-icon'))return;e.preventDefault();e.stopImmediatePropagation();e.dataTransfer.dropEffect=window.decklabLivePreview?'none':'copy';},true);
  $('profileDeck').addEventListener('drop',async e=>{const raw=e.dataTransfer.getData('application/x-decklab-elgato-icon');if(!raw)return;e.preventDefault();e.stopImmediatePropagation();if(window.decklabLivePreview||profileDevice().inputOnly)return;const node=e.target.closest('[data-art-controller]');if(!node)return;const page=profilePage(),device=profileState.target,controller=node.dataset.artController,column=Number(node.dataset.artColumn),row=Number(node.dataset.artRow);try{const data=JSON.parse(raw),item=await raster(data.id,data.colour);if(page!==profilePage()||device!==profileState.target||window.decklabLivePreview)return;let p=profilePlacementAt(controller,column,row);if(!p)p=await createProfileActionPlacement(profileAvailableActions().findIndex(a=>a.UUID==='com.decklab.visual'),controller,column,row);if(p){apply(p,item);selectProfilePlacement(p);$('artworkStatus').textContent='Applied '+item.meta.name;}}catch(e){$('artworkStatus').textContent=e.message;}},true);
 }
 window.DeckLabElgatoIcons={load,raster,draw,cancel:()=>generation++};document.addEventListener('DOMContentLoaded',()=>setTimeout(boot,480));
})();
