// SPDX-License-Identifier: MPL-2.0
/* Documented icon-pack reader: data only. SVG imports are rasterised after validation. */
(function(root){
 const safe=path=>typeof path==='string'&&!path.startsWith('/')&&!path.includes('\\')&&!path.includes(':')&&!path.split('/').includes('..');
 async function read(files){const roots=[...files.keys()].filter(p=>/(^|\/)manifest.json$/i.test(p)&&files.has(p.slice(0,-13)+'icons.json'));if(roots.length!==1)throw Error('Choose one icon pack with manifest.json and icons.json.');const base=roots[0].slice(0,-13),json=p=>JSON.parse(new TextDecoder().decode(files.get(p))),manifest=json(roots[0]),index=json(base+'icons.json');if(!manifest.Name||!Array.isArray(index)||index.length>1000)throw Error('Invalid icon-pack metadata or more than 1,000 icons.');
 const licencePath=manifest.License||manifest.Licence;const license=safe(licencePath)&&files.has(base+licencePath)?new TextDecoder().decode(files.get(base+licencePath)).slice(0,100000):'';const entries=[];
 for(const icon of index){if(!safe(icon.path))throw Error('Unsafe icon path.');const path=base+'icons/'+icon.path,bytes=files.get(path);if(!bytes)throw Error('Missing indexed icon: '+icon.path);const ext=path.split('.').pop().toLowerCase(),mime={png:'image/png',jpg:'image/jpeg',jpeg:'image/jpeg',gif:'image/gif',webp:'image/webp',svg:'image/svg+xml'}[ext];if(!mime)throw Error('Unsupported image: '+icon.path);let binary='';for(let i=0;i<bytes.length;i+=16384)binary+=String.fromCharCode(...bytes.subarray(i,i+16384));let data='data:'+mime+';base64,'+btoa(binary);
 if(ext==='svg'){const xml=new TextDecoder().decode(bytes),doc=new DOMParser().parseFromString(xml,'image/svg+xml');if(doc.querySelector('parsererror')||doc.documentElement.localName!=='svg'||/<!DOCTYPE|<!ENTITY/i.test(xml))throw Error('Invalid SVG: '+icon.path);for(const el of doc.querySelectorAll('*')){if(['script','foreignObject','iframe','style','image','use','animate','set','animateTransform','animateMotion'].includes(el.localName))throw Error('Unsupported active or referenced SVG content: '+icon.path);for(const a of el.attributes)if(/^on/i.test(a.name)||/href|src/i.test(a.name)||/url\s*\(/i.test(a.value))throw Error('External or active SVG content: '+icon.path);}const img=new Image();img.src=data;await img.decode();const c=document.createElement('canvas');c.width=c.height=144;c.getContext('2d').drawImage(img,0,0,144,144);data=c.toDataURL('image/png');}
 entries.push({name:String(icon.name||icon.path),data,meta:{pack:String(manifest.Name),author:String(manifest.Author||''),version:String(manifest.Version||''),license,tags:Array.isArray(icon.tags)?icon.tags.map(String):[],sourcePath:icon.path,svgRasterized:ext==='svg'}});
 }return {manifest,entries};}
 root.DeckLabIconPack={read,safe};
})(window);
