// SPDX-License-Identifier: MPL-2.0
/* Explicit user-triggered simulations, independent of operating-system monitoring. */
(function(){
 const $=id=>document.getElementById(id);let running=false;
 const oldMulti=renderMultiActionEditor;
 renderMultiActionEditor=function(){oldMulti();const p=selectedProfilePlacement();if(!p?.sequences)return;const seq=p.sequences[profileState.multiSequence]||[];[...$('multiStepList').children].forEach((row,i)=>{const st=seq[i];if(!st)return;const sub=row.querySelector('.multi-step-sub');if(sub){sub.textContent=st.kind==='wait'?'Delay · milliseconds':'Action · '+(Number(st.state)?'B':'A');sub.title=st.context||'';}const copy=document.createElement('button');copy.className='secondary';copy.textContent='Copy';copy.title='Duplicate step';copy.setAttribute('aria-label','Duplicate step '+(i+1));copy.onclick=()=>{if(p._running)return;profilePushHistory('duplicate step');const next=st.kind==='wait'?{kind:'wait',id:'wait-'+(++profileState.stepCounter),duration:st.duration}:createMultiActionStep(st.actionIndex,p,profileState.multiSequence,st);seq.splice(i+1,0,next);renderProfileLab();profileScheduleAutosave();};row.insertBefore(copy,row.lastChild);if(st.kind==='wait'){const duration=document.createElement('input');duration.type='number';duration.min=0;duration.max=60000;duration.value=st.duration;duration.setAttribute('aria-label','Delay in milliseconds');duration.onchange=()=>{profilePushHistory('edit delay');st.duration=Math.max(0,Math.min(60000,Number(duration.value)||0));renderMultiActionEditor();profileScheduleAutosave()};row.querySelector('.multi-step-title').replaceChildren(duration);}row.querySelectorAll('button,input').forEach(b=>b.disabled=p._running||b.disabled);});};
 function refresh(){const page=$('simulationPage');if(!page)return;const value=page.value;page.replaceChildren();for(const p of profileState.pages)page.add(new Option(p.name,p.id,false,p.id===value));const group=$('simulationDials');group.replaceChildren();for(const p of profileState.placements.filter(p=>p.pageId===profileState.currentPageId&&p.controller==='Encoder')){const label=document.createElement('label'),check=document.createElement('input');check.type='checkbox';check.value=p.id;check.checked=true;label.append(check,document.createTextNode('Dial '+(p.column+1)+' · '+(profileActionFor(p)?.Name||'Action')));group.append(label);}}
 async function run(kind){if(running)return;const p=selectedProfileInstance();if(!p){$('simulationStatus').textContent='Select an action first.';return;}if(!profileState.connected){$('simulationStatus').textContent='Connect the virtual device first.';return;}running=true;try{const emit=(e,x={})=>profileEmitInput(p,e,x),pause=ms=>new Promise(r=>setTimeout(r,ms));if(kind==='touch'){if(!['Encoder','Neo'].includes(p.controller))throw Error('Select a touch-capable action.');emit('touchTap',{tapPos:[50,25],hold:true});}else{const down=p.controller==='Encoder'?'dialDown':'keyDown',up=p.controller==='Encoder'?'dialUp':'keyUp';if(p.controller==='Neo')throw Error('Use touch hold for the Neo Infobar.');emit(down);await pause(kind==='hold'?700:70);emit(up);if(kind==='double'){await pause(120);emit(down);await pause(70);emit(up);}}$('simulationStatus').textContent='Sent '+kind+' gesture to '+(profileActionFor(p)?.Name||'action')+'. Interpretation belongs to the action.';}catch(e){$('simulationStatus').textContent=e.message}finally{running=false}}
 function boot(){const panel=document.createElement('details');panel.className='studio-details';panel.id='interactionTools';panel.innerHTML='<summary>Interaction scenarios</summary><p class="hint">Manual host simulations. These do not monitor or control applications.</p><div class="creator-actions"><button data-gesture="hold" class="secondary">Hold</button><button data-gesture="double" class="secondary">Double press</button><button data-gesture="touch" class="secondary">Touch hold</button></div><h4>Dial group</h4><div id="simulationDials"></div><button id="simulationRotate" class="secondary">Rotate selected dials +1</button><h4>Application condition</h4><label>Application name<input id="simulationApplication" placeholder="e.g. Photoshop"></label><label>Target page<select id="simulationPage"></select></label><button id="simulationActivate" class="secondary">Simulate application → page</button><p id="simulationStatus" class="hint" role="status"></p>';document.querySelector('.builder-inspector-panel').append(panel);panel.ontoggle=()=>{if(panel.open)refresh()};panel.querySelectorAll('[data-gesture]').forEach(b=>b.onclick=()=>run(b.dataset.gesture));$('simulationRotate').onclick=()=>{if(!profileState.connected)return;$('simulationDials').querySelectorAll('input:checked').forEach(c=>{const p=profileState.placements.find(p=>p.id===c.value);if(p)profileEmitInput(p,'dialRotate',{ticks:1,pressed:false})});$('simulationStatus').textContent='Rotated the selected dial group.'};$('simulationActivate').onclick=()=>{const app=$('simulationApplication').value.trim(),page=$('simulationPage').value;if(!app){$('simulationStatus').textContent='Enter an application name.';return;}logProfile('simulatedApplicationCondition',{application:app,page});navigateProfilePage(page,'simulated application: '+app);$('simulationStatus').textContent=app+' simulated → '+(profileState.pages.find(p=>p.id===page)?.name||page)+'. No OS process was started.';};}
 document.addEventListener('DOMContentLoaded',()=>setTimeout(boot,300));
})();
